set(_CATKIN_CURRENT_PACKAGE "dynamic_detection")
set(dynamic_detection_VERSION "0.0.0")
set(dynamic_detection_MAINTAINER "pf <pf@todo.todo>")
set(dynamic_detection_PACKAGE_FORMAT "1")
set(dynamic_detection_BUILD_DEPENDS "sensor_msgs" "roscpp")
set(dynamic_detection_BUILD_EXPORT_DEPENDS "sensor_msgs" "roscpp")
set(dynamic_detection_BUILDTOOL_DEPENDS "catkin")
set(dynamic_detection_BUILDTOOL_EXPORT_DEPENDS )
set(dynamic_detection_EXEC_DEPENDS "sensor_msgs" "roscpp")
set(dynamic_detection_RUN_DEPENDS "sensor_msgs" "roscpp")
set(dynamic_detection_TEST_DEPENDS )
set(dynamic_detection_DOC_DEPENDS )
set(dynamic_detection_DEPRECATED "")