set(_CATKIN_CURRENT_PACKAGE "map_load")
set(map_load_VERSION "0.0.0")
set(map_load_MAINTAINER "pf <pf@todo.todo>")
set(map_load_PACKAGE_FORMAT "1")
set(map_load_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(map_load_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(map_load_BUILDTOOL_DEPENDS "catkin")
set(map_load_BUILDTOOL_EXPORT_DEPENDS )
set(map_load_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(map_load_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(map_load_TEST_DEPENDS )
set(map_load_DOC_DEPENDS )
set(map_load_DEPRECATED "")